# Site settings
title: Your awesome title
email: exec@socis.ca
description: ""
url: "http://uogsocis.github.io"
facebook_url: "https://www.facebook.com/groups/UoGSOCIS/"
twitter_url: "https://twitter.com/uogsocis"

# Build settings
markdown: redcarpet
permalink: /posts/:year/:month/:day/:title
timezone: America/New_York
